### ISSUE TITLE
Variablize GitHub Actions versions

### ISSUE THREAD

**Issue by rchildress87** [StratusGrid/workflow-config#35]
The same Actions versions are being duplicated in each job. I think we should replace with environment versions and version tags to simplify updates and improve readability.

Current state:
```yaml
env:
  PY_VERSION: "3.10"
  GO_VERSION: "^1.19.0"

jobs:
  terraform_fmt:
    name: terraform_fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3
```

Proposed state:
```yaml
env:
  ACTIONS_SETUP_GO_VERSION: "v3"
  PY_VERSION: "3.10"
  GO_VERSION: "^1.19.0"

jobs:
  terraform_fmt:
    name: terraform_fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@${{ env.ACTIONS_SETUP_GO_VERSION }}
```
